name: Challenge App CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
  pull_request:
    branches:
      - main
    paths:
      - 'app/**'

permissions:
  contents: write

env:
  APP_CHART_VALUES_PATH: ./1_infrastructure/terraform/app-chart/values.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.0

      - name: Build
        run: |
          ./scripts/compile.sh

      # - name: Lint and Test
      #   run: |
      #     Here we should run the corresponding test for our Go app.
      #     Additionally, we should run linters to guarantee the code quality and style.

      - name: Set Version
        id: vars
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GHCR
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      
      - name: Build and Push Docker Image
        env:
          IMAGE_NAME: ghcr.io/carlaurr/challenge
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t "$IMAGE_NAME:$IMAGE_TAG" \
            -t "$IMAGE_NAME:latest" \
            .

      - name: Update Helm Chart
        if: github.ref == 'refs/heads/main'
        run: |
          sed -i 's|tag: .*|tag: '"$IMAGE_TAG"'|' ${{ env.APP_CHART_VALUES_PATH }}

      - name: Commit and Push Helm Chart Update
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.email "ci-bot@xyz.com"
          git config --global user.name "CI Bot"
          git add ${{ env.APP_CHART_VALUES_PATH }}
          git commit -m "release: Update image tag to $IMAGE_TAG"
          git push origin main
  